zc=int(input("Introduceti ziua curenta:",17))
lc=int(input("Introduceti luna curenta:",10))
ac=int(input("Introduceti anul curent:",2020))
zn=int(input("Introduceti ziua nasterii:",18))
ln=int(input("Introduceti luna nasterii:",12))
an=int(input("Introduceti anul nasterii:",2004))
if (lc>ln)
   print((ac-an)+1)
else print(ac-an)