n1=int(input("Introduceti prima nota:",7))
n2=int(input("Introduceti a doua nota:",8))
n3=int(input("Introduceti a treia nota:",9))
if (n3>8)
   print(n1,n2,n3)
if (n3<8)
if (n1>n2)
   print(n1)
if (n2>n1)
   print(n2)
